name: Setup Terraform Backend State Storage and Initialize main resource group

on:
  [push]

env:
  SHORT_NAME: scalesets  
  LOCATION: 'eastus2'
  TAGS: 'Org=ssa DeployedBy=terraform Environment=prod OwnerEmail=DL-P7-OPS@p7.com Platform=na'        

jobs:
  Main-Terraform:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Terraform Setup
      id: tfsetup
      uses: fluffy-bunny/action-docker-azure-terraform-setup@v0.3-alpha
      with:
        shortName: ${{ env.SHORT_NAME }}
        location: ${{ env.LOCATION }}
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        tags: ${{ env.TAGS }}

    - name: Get the output tfsetup
      shell: bash
      run: |
        echo "The storage_account_name was:   '${{ steps.tfsetup.outputs.storage_account_name }}'"
        echo "The container_name was:         '${{ steps.tfsetup.outputs.container_name }}'"
        echo "The secret_name was:            '${{ steps.tfsetup.outputs.secret_name }}'"
        echo "The keyvault_name was:          '${{ steps.tfsetup.outputs.keyvault_name }}'"


    - name: 'az login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    
    
  
     
